Initial RM CI Pipelines
ONSdigital/census-rm-deploy pull request #1
Opened 2019-02-04 16:06 UTC by AdamHawtin

### Motivation and Context
These are pipelines for deploying the RM services to a CI environment in kubernetes. There are two pipelines in this PR, the `ci-kubernetes-pipeline.yml` runs through the kubernetes configuration files for the RM services, deploying them based on master in the census-rm-kubernetes repo. The `ci-latest-patch-pipeline.yml` checks for new builds of each RM service image latest tag in the container registry, then runs a `kubectl patch` with a timestamp to trigger kubernetes to pull the newly built image. 

The pipelines are running in the census concourse and have successfully deployed and updated the RM services.

### What has Changed
- New pipeline to deploy RM based on census-rm-kubernetes configuration
- New pipeline to trigger kubernetes to pull newly built latest tagged images
- New example secrets
- Updated README
- Updated gitignore

### Links
https://trello.com/c/pnfYl0em/435-concourse-13

2019-02-04 16:07 UTC, AdamHawtin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Concourse (13)](https://trello.com/c/pnfYl0em/435-concourse-13)

2019-02-11 08:59 UTC, davidmort requested changes

2019-02-11 08:59 UTC, davidmort commented on README.md
> +The first pulls from the `census-rm-kubernetes` repo triggered by commits to master and applies the latest microservice and handler configs to the kubernetes cluster specified by the pipeline configu
could make "census-rm-kubernetes" a link to the repo

2019-02-11 08:59 UTC, davidmort commented on README.md
> +| kubernetes-server | https://\<host>:\<port> | The URL of the kubernetes server endpoint |
Might be worth mentioning "master" in the description, just to be specific.....

2019-02-11 08:59 UTC, davidmort commented on README.md
> +| kubernetes-token | JWT String | A JWT access token. Must be for an account with the required roles in kubernetes |
might be worth being a bit more specific and mention "service account" not just "account" in the description

2019-02-12 08:32 UTC, davidmort approved these changes

2019-02-12 08:50 UTC, kierenbeckett commented
`kubectl rollout status deployment <deployment>`

2019-02-13 09:46 UTC, davidmort approved these changes

2019-02-13 12:56 UTC, liamtoozer approved these changes

2019-02-13 13:10 UTC, merged