Deploy infrastructure to blacklodge
ONSdigital/census-rm-deploy pull request #114
Opened 2019-12-12 13:59 UTC by liamtoozer

# Motivation and Context

We need to be able to trigger automated infrastructure deployments in our Blacklodge pipeline using tagged releases.

# What has changed

Updated the manual release pipeline

# How to test?

Fly

# Links

https://trello.com/c/KTWj2B55/419-use-concourse-to-deploy-blacklodge-infrastructure-5

2019-12-12 14:00 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Use concourse to deploy Blacklodge infrastructure (5)](https://trello.com/c/KTWj2B55/419-use-concourse-to-deploy-blacklodge-infrastructure-5)

2019-12-13 08:18 UTC, AdamHawtin requested changes
I think this pipeline needs groups now to easily view the overview/infrastructure/app deployments as they all get mixed together in the UI.

Regarding the failure slack messages, I see they are missing from other pipelines as well so I'll raise a small ticket to add alerts into other pipelines where they are missing as well.

2019-12-13 08:18 UTC, AdamHawtin commented on pipelines/manual-release-pipeline.yml
> +- name: "Run Terraform"
This job needs a failure slack message

2019-12-13 08:18 UTC, AdamHawtin commented on pipelines/manual-release-pipeline.yml
> +- name: "Run Rabbit Helm"
This job needs a failure slack message

2019-12-13 08:34 UTC, liamtoozer commented
> I think this pipeline needs groups now to easily view the overview/infrastructure/app deployments as they all get mixed together in the UI.

We thought about doing this but wasn't sure if it should have been a separate piece of work as it adds a little more complexity to the ticket (not much though!). Happy to do it though as it shouldn't take long?

2019-12-13 09:14 UTC, AdamHawtin commented
@liamtoozer I think we need to keep the pipelines organised, they're already getting pretty big and anything we can do to keep them clear and understandable in the UI helps.

2019-12-13 09:39 UTC, AdamHawtin approved these changes

2019-12-13 09:45 UTC, hbrace approved these changes

2019-12-13 09:48 UTC, merged