Changing groundzero location
ONSdigital/census-rm-deploy pull request #127
Opened 2020-01-31 15:29 UTC by ryangrundy7

# Motivation and Context

Updated the groundzero script in the performance environment to use the groundzero from the ddl repo instead of the toolbox repo.

# What has changed

- Groundzero runs from ddl repo instead of toolbox

# Links
[Trello](https://trello.com/c/rnYxcW1Z)

2020-01-31 15:30 UTC, ryangrundy7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Performance environment needs to rebuild the DB using the groundzero script which matches the release it's testing (5)](https://trello.com/c/rnYxcW1Z/540-performance-environment-needs-to-rebuild-the-db-using-the-groundzero-script-which-matches-the-release-its-testing-5)

2020-02-03 09:27 UTC, AdamHawtin approved these changes

2020-02-03 09:27 UTC, AdamHawtin requested changes

2020-02-03 09:27 UTC, AdamHawtin commented on tasks/kubectl-run-groundzero-script.yml
> +    - |
Duplicate lines

2020-02-03 09:29 UTC, liamtoozer approved these changes
LGTM 👍

2020-02-03 09:44 UTC, ryangrundy7 commented on tasks/kubectl-run-groundzero-script.yml
> +    - |
Fixed

2020-02-03 10:39 UTC, NickGrantX approved these changes
LGTM 👍

2020-02-03 13:15 UTC, AdamHawtin approved these changes

2020-02-03 14:12 UTC, merged