Add multiple jobs to trigger different performance tests
ONSdigital/census-rm-deploy pull request #137
Opened 2020-02-17 14:53 UTC by NickGrantONS

# Motivation and Context
30 million takes ages. 3.5 million takes 3 hours. 350k takes 40 minutes. PubSub takes a couple of minutes. We want a way to run the test we want, not have to run ALL of them.

# What has changed
Added multiple trigger jobs for different poipoises.

# How to test?
Fly. Fly. Fly.

# Links
Trello: https://trello.com/c/zWLwrX72

2020-02-17 15:19 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [SPIKE: Multiple trigger jobs for performance pipeline for different types of test (2 days)](https://trello.com/c/zWLwrX72/620-spike-multiple-trigger-jobs-for-performance-pipeline-for-different-types-of-test-2-days)

2020-02-17 15:31 UTC, AdamHawtin requested changes
Failing build as you can't have a repeated `get` for the same resource in a job. I think you might be able to make this work by making the 3 "selection" jobs separate from a single trigger job, which will just trigger the pipeline with whatever selection was last made (so the process for running a specific test would be run the selection job, then after it finished run the trigger job to kick them off).

Neat idea having them write the choice to a bucket by the way!

2020-02-17 17:05 UTC, NickGrantONS commented
Check out my latest hackery @AdamHawtin

2020-02-18 08:49 UTC, AdamHawtin commented on pipelines/performance-tests-pipeline.yml
> +    trigger: true
These are going to trigger the job every minute

2020-02-18 09:53 UTC, AdamHawtin approved these changes

2020-02-18 09:56 UTC, ryangrundy7 approved these changes
Looks good to me 👍 🤞

2020-02-18 10:00 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Allow performance test choice before triggering](https://trello.com/c/GcUinqJS/632-allow-performance-test-choice-before-triggering)

2020-02-18 10:00 UTC, liamtoozer approved these changes
LGTM 👍

2020-02-18 12:40 UTC, merged