Added Case Processor
ONSdigital/census-rm-deploy pull request #14
Opened 2019-04-18 13:42 UTC by NickGrantONS

# Motivation and Context
We have a new Case Processor service, which we want to deploy in CI and run acceptance tests against.

# What has changed
Added the Case Processor.

# How to test?
Fly the pipeline. It should go green.

# Links
Trello: https://trello.com/c/wj2LhC2Z/642-case-service-a-new-hope-13

2019-04-18 14:29 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Case service: A New Hope (13)](https://trello.com/c/wj2LhC2Z/642-case-service-a-new-hope-13)

2019-04-23 12:55 UTC, AdamHawtin requested changes
The pipeline looks fine but the new service running in CI appears to be causing issues, it may be maxing out the database connection pool.

EDIT - Looks like this branch might just have been missing some config that was merged into master.

2019-04-24 07:08 UTC, AdamHawtin approved these changes

2019-04-25 13:19 UTC, nealedj approved these changes

2019-04-25 13:21 UTC, merged