Added new pubsub service to performance pipeline.
ONSdigital/census-rm-deploy pull request #167
Opened 2020-05-15 13:09 UTC by apolloakora

# Motivation and Context
Adding the new pubsub service to the performance test pipeloine.

# What has changed
The naming of the performance tests. The more significant changes are in the kubernetes repo which has the queue definitions.

# How to test?
Run the performance test pipeline in gcloud and view the grafana dashboard for anomalies and compare the results to what is tentatively expected.

2020-05-15 13:18 UTC, AdamHawtin commented on pipelines/performance-tests-pipeline.yml
> +    pubsub-adaptersvc,
For consistency with the other pipeline I'd rather this was just `pubsub-adapter`

2020-05-15 13:19 UTC, AdamHawtin requested changes
Changes make sense, just a small request for naming consistency 👍

2020-05-15 13:26 UTC, apolloakora commented
![](https://github.trello.services/images/mini-trello-icon.png) [Replace python pubsub service with pubsub-adapter in performance pipeline (5)](https://trello.com/c/0iQgvsBW/921-replace-python-pubsub-service-with-pubsub-adapter-in-performance-pipeline-5)

2020-05-19 13:26 UTC, AdamHawtin approved these changes

2020-05-19 14:14 UTC, NickGrantX requested changes
please remove the `svc` suffix

2020-05-20 10:33 UTC, NickGrantONS commented on pipelines/performance-tests-pipeline.yml
> +- name: "PubSub Adapter Service"
just "PubSub Adapter"

2020-05-20 10:33 UTC, NickGrantONS commented on pipelines/performance-tests-pipeline.yml
> +      "PubSub Adapter Service",
Just "PubSub Adapter"

2020-05-20 10:37 UTC, NickGrantX approved these changes
LGTM 👍

2020-05-20 10:40 UTC, merged