First Creation of Ops-UI
ONSdigital/census-rm-deploy pull request #200
Opened 2020-08-04 14:08 UTC by LeoKHoward

First stab at creating census-rm-ops-ui repo

2020-08-04 14:22 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [R Ops - hello world (5)](https://trello.com/c/bM1S1Jpw/1242-r-ops-hello-world-5)

2020-08-06 06:40 UTC, AdamHawtin commented on pipelines/manual-release-pipeline.yml
> +             "Ops UI Tool"
No need to trigger the whitelisting, we won't be using it with this new UI.

2020-08-06 06:42 UTC, AdamHawtin requested changes
Looks good, should probably add the deployment to the performance pipeline as well.

2020-08-10 08:58 UTC, AdamHawtin commented on pipelines/build-deploy-test-CI-WL.yml
> +- name: "CI Deploy Ops UI Tool"
I'd rather stick to the name "Ops UI" without "Tool" to avoid confusing it any more with the testing "Ops Tool"

2020-08-10 11:31 UTC, AdamHawtin approved these changes
LGTM

2020-08-10 14:03 UTC, ryangrundy7 approved these changes

2020-08-10 17:20 UTC, merged