Togglerable RabbitMQ Node Pools
ONSdigital/census-rm-deploy pull request #237
Opened 2021-02-08 09:03 UTC by apolloakora

We need to be able to create a second rabbitmq node-pool to seamlessly move to.

The RabbitMQ second/standby node pool will also be under Terraform's control. The rabbit node pools will be toggleable.
This will be accompanied by a runbook and can be invoked to handle expected high CPU and/or memory pressure.

2021-02-08 09:08 UTC, apolloakora commented
![](https://github.trello.services/images/mini-trello-icon.png) [RabbitMQ - Add Standby Node Pool (8)](https://trello.com/c/mqU3MLoP/1973-rabbitmq-add-standby-node-pool-8)

2021-02-08 09:12 UTC, NickGrantONS requested changes
I disagree that making Concourse the place where we change the node pool being used is the right place to change things

2021-02-08 09:14 UTC, NickGrantONS commented on pipelines/manual-release-pipeline.yml
> +      NODE_POOL_NAME: ((node-pool-name))
this is undefined

2021-02-08 09:15 UTC, NickGrantONS commented on pipelines/performance-tests-pipeline.yml
> +        NODE_POOL_NAME: ((node-pool-name))
this is undefined

2021-02-08 09:15 UTC, NickGrantONS commented on pipelines/prod-manual-release-pipeline.yml
> +      NODE_POOL_NAME: ((node-pool-name))
this is undefined

2021-02-09 09:57 UTC, apolloakora commented
Not using concourse to deploy the standby node pool any more.

2021-02-09 09:57 UTC, closed without merging