Removal of Timestamp Patch Related To Prod Manual Release Pipeline
ONSdigital/census-rm-deploy pull request #239
Opened 2021-02-16 12:41 UTC by LeoKHoward

# Motivation and Context
Currently, our concourse jobs will force a rolling restart even if that same tag is already deployed. This is because we patch the deployment to force a re-deploy due to the k8s/docker latest tag issue

# What has changed
Removed timestamp patch line from 3 .yml task files related to prod manual release

# How to test?
Deploy and look at it manually

# Links
https://trello.com/c/K2UJSyL2

2021-02-16 12:42 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [fix concourse deploy jobs for preprod/prod (8)](https://trello.com/c/K2UJSyL2/2041-fix-concourse-deploy-jobs-for-preprod-prod-8)

2021-02-16 16:42 UTC, NickGrantONS requested changes
mistake by me

2021-02-16 16:47 UTC, NickGrantONS approved these changes
Looks good to me 👍

2021-02-17 09:08 UTC, hbrace approved these changes

2021-02-18 10:25 UTC, merged