census-qid-batch-runner image change to trigger acceptance tests
ONSdigital/census-rm-deploy pull request #24
Opened 2019-06-06 11:42 UTC by liamtoozer

# Motivation and Context

We want to trigger the acceptance tests whenever the census-rm-qid-batch-loader image changes. 

# What has changed

Updated the 3 pipeline configs

# How to test?

This has already been fly'd in CI. You should be able to see the `qid-batch-runner-docker-latest` resource just before the acceptance test job.

# Links

https://trello.com/c/tT4XZ09B/784-acceptance-tests-for-unaddressed-print-files-13

2019-06-06 12:02 UTC, liamtoozer commented
![](https://github.trello.services/images/mini-trello-icon.png) [Acceptance tests for unaddressed print files (13)](https://trello.com/c/tT4XZ09B/784-acceptance-tests-for-unaddressed-print-files-13)

2019-06-07 14:02 UTC, hbrace approved these changes

2019-06-10 08:29 UTC, NickGrantX approved these changes
LGTM 👍

2019-06-11 08:20 UTC, AdamHawtin requested changes

2019-06-11 08:20 UTC, AdamHawtin commented on pipelines/manual-ci-kubernetes-pipeline.yml
> +    trigger: true
Shouldn't have a trigger in the manual pipeline.

2019-06-12 08:31 UTC, AdamHawtin approved these changes

2019-06-12 08:54 UTC, jcox-dev approved these changes

2019-06-13 09:15 UTC, merged