Add slack alerts on job failure
ONSdigital/census-rm-deploy pull request #53
Opened 2019-08-01 11:35 UTC by jcox-dev

# What has changed

- Added slack alerts on most job failures
- Added slack alerts on terraform start/success/fail
- Expects new `((slack.webhook))` config

# How to test?

Read *every* 2815 lines that have been added to make sure everything is as it seems.

2019-08-01 13:06 UTC, kierenbeckett reviewed
:+1: Let me know if you need `slack.webhook` adding to the central concourse

2019-08-02 07:43 UTC, AdamHawtin requested changes
Could save a few code lines by defining the slack on failure component with an alias so it can be reused, like:
```yaml
slack_failure_alert : &slack_failure_alert 
      put: slack-alert
      params:
        icon_emoji: ":concourse:"
        username: Concourse
        attachments: [
              {
                  "fallback": "$BUILD_JOB_NAME failed. See build: $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME",
                  "title": "$BUILD_JOB_NAME failed",
                  "title_link": "$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME",
                  "fields": [
                      {
                          "title": "Pipeline",
                          "value": "$BUILD_PIPELINE_NAME",
                          "short": true
                      },
                      {
                          "title": "Build",
                          "value": "#$BUILD_NAME",
                          "short": true
                      }
                  ],
                  "color": "#F35A00"
              }
          ]
```

Then referred to like
```yaml
on_failure: *slack_failure_alert
```

2019-08-02 13:23 UTC, AdamHawtin approved these changes
LGTM 👍

2019-08-02 13:24 UTC, ryangrundy7 approved these changes
LGTM 👍

2019-08-02 13:30 UTC, AdamHawtin commented on .travis.yml
> +  - for i in pipelines/*.yml; do ./fly validate-pipeline -c $i; done
👍

2019-08-02 13:31 UTC, merged