Add Exception Manager to Concourse
ONSdigital/census-rm-deploy pull request #70
Opened 2019-10-10 12:11 UTC by NickGrantONS

# Motivation and Context
We need an exception manager to help us deal with unprocessable messages with zero downtime.

# What has changed
Added Exception Manager to the pipeline.

# How to test?
Fly the pipeline and let her rip!

# Links
Trello: https://trello.com/c/f7LmzvJm

2019-10-10 12:16 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [SPIKE: zero downtime message quarantine and error log reduction (5 days)](https://trello.com/c/f7LmzvJm/1244-spike-zero-downtime-message-quarantine-and-error-log-reduction-5-days)

2019-10-10 15:21 UTC, NickGrantONS commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exception Manager v1.0](https://trello.com/c/2rkYNAMa/1266-exception-manager-v10)

2019-10-11 09:39 UTC, ryangrundy7 commented on pipelines/ci-sit-kubernetes-pipeline.yml
> +      docker-image-resource: cexception-manager-docker-latest,
Spelling mistake: `cexception `

2019-10-11 09:41 UTC, ryangrundy7 requested changes
Looks good, just a mistake for one of the docker resources

2019-10-11 11:44 UTC, ryangrundy7 approved these changes

2019-10-14 08:27 UTC, liamtoozer approved these changes

2019-10-15 08:54 UTC, merged